# Generated by Django 5.0.7 on 2024-08-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='publico_alvo',
            field=models.CharField(choices=[('B2B', 'B2B (Business To Business)'), ('B2C', 'B2C (Business To Client)')], max_length=3),
        ),
    ]
